### ISSUE TITLE
Possible to use with berhinger?

### ISSUE THREAD

**Issue by eldondev** [FMMT666/launchpad.py#16]
I am interested in this project, but don't have previous experience with this type of musical creation, and do not have a lot of room in the budget for new equipment.
There is a similar piece of hardware to the launchpad called the BEHRINGER CMD TOUCH TC64 Controller, which can be purchased on ebay for ~60% of the launchpad mini. It also seems to have some sort of "launchpad compatibility mode". I was wondering if anyone had an idea if this would likely work with that piece of hardware as well, or could be made to work with it? I understand Linux and USB protocols well, but am mostly unfamiliar with MIDI, so I might be able to help a little, but am not sure I could add support for myself.

**Comment by FMMT666** [comment]
I already acquired a Behringer CMD DC-1, some time ago,
but those SysEx messages (and that I really don't have that
much time right now :-) issues stopped any progress on that.
It shouldn't be too much complicated, though...

**Comment by dish-eme-sdr** [comment]
With all due respect, I believe a Behringer CMD DC-1 and a Behringer CMD Touch TC64 are two completely different animals!  I do NOT own a DC-1.  But I do own SIX of the Behringer CMD Touch TC64!  And I got them from the sale on eBay mentioned in the first post.

I have tested the Behringer CMD Touch TC64 with every version of Ableton that I could get my hands on under OS X, XP, Win7, and on a Dell mini9 Hackintosh which runs OS X, XP, Win7 and Debian Linux, and (after finding the wonderful work done by FMMT666, raspberry pi 3.

In all cases, EVERYTHING WORKS.  No, patches, no setup, NOTHING !!!

I am able to download project files seen on YouTube and play the files using the Behringer CMD Touch TC64 (in launchpad compatibility mode).  If there are any compatibility issues, I haven't seen them.  Everything works, including the lights.

Of course, keep in mind (like the earlier launchpads) the Behringer CMD Touch TC64 has only RED / GREEN lights (both on full produce yellow), so just like the older model Launchpads, you aren't going to see any blue lights !!!!  The two colors respond to 0, 1, 2, and 3 with 0,3 producing green, 3,0 producing red, and 3,3 producing yellow.  Just as expected!  If 1 or 2 is substituted for a 0 or a 3, you get a dimmer light of the same color.  So you can mix to produce colors like orange, etc.

I'm sure you already know this, but all that is required to put the CMD 64 in '-Launchpad compatibility mode-' is to hold down the two mode buttons (these are the two buttons in the extreme upper left hand corner of the unit) WHILE YOU PLUG IN THE USB CORD.  The two buttons should flash red, then go out.  You are now in '-Launchpad compatibility mode-' and the unit will remember this mode even when it's powered down then back up.  So you don't have to do this every time you power it up.  Mine have been in launchpad compatibility mode since I took them out of the box and NONE have reverted back to Behringer mode.

I have read all kinds of reports of people having '-issues-' with the Behringer CMD Touch TC64 of lights not working or producing the wrong colors, some buttons not working as expected, etc.  That has NOT been my experience.  I have to assume the people having these issues would have the same issues using a genuine Launchpad.

As mentioned, I have launchpad.py running on a raspberry pi 3.  I have run as many as SIX Behringer CMD Touch TC64 simultaneously with no issues.  Once you go past four though you're going to need some kind of hub as the raspberry only has four USB ports.  And a powered hub would be a very good idea as more than four starts to pull a good bit of current as that's a LOT of LEDs lighting up!

It's been my finding that the raspberry pi 3 is the way to go as it has a LOT faster response (using launchpad.py) than say, Ableton running on OS X, Windows, etc. as there is a LOT less '-bloatware-' between your fingers and the music!!!

I hope this helps.

In fact, I've been a lurker on github for YEARS but broke down and joined just a few minutes ago, just so I could set the record straight on the Behringer CMD Touch TC64.

My advice?  Buy as many as you can afford before they are all gone....  Musicgroup1 has sold over a 1000 of these on eBay and if I have it figured right, he's on the final 100 as of today....

**Comment by dish-eme-sdr** [comment]
One thing I forgot to mention:

When the Behringer CMD Touch 64 is running in '-Launchpad compatibility mode-', launchpad.py identifies the Behringher as the following:

Launchpad Mk1/S/Mini

I thought this bit of info might be helpful to someone...

**Comment by eldondev** [comment]
I also picked up 3 of these :smile: . Yes, they seem to work pretty much out of the box. I am going to close this issue.
