### ISSUE TITLE
Do you plan on porting it to Python 3 ? 

### ISSUE THREAD

**Issue by nukadelic** [FMMT666/launchpad.py#26]
.

**Comment by malmeloo** [comment]
That'd be really great! This seems like the package that suits my needs best, but I only use python 3...

**Comment by FMMT666** [comment]
Actually we're horribly busy with playing Splatoon
on the Switch, but well - why not? :-)

This won't work on all systems because of the different platform
dependent MIDI implementations of PyGame.
Probably only a few would consider compiling patched PyGame
on their on, only for this.

I will test some things...

**Comment by Reaxt** [comment]
if you can, please do.

**Comment by FMMT666** [comment]
Done [tm], as in "works on one of my systems":
Windows 10, Python 3.6.4, PyGame 1.9.3 (via pip).

Go and give it a try (and report, please)...

It will, for example, not work on a stock Ubuntu 16.04.3-LTS,
at least not without compiling a new PyGame (ALSA, PortMidi) version.

**Comment by FMMT666** [comment]
Done. Tested on macOS, Windoue 7/10.
It doesn't work on all Linux systems yet, due to some build related
issues in PyGame and ALSA (...), but I can probably provide an
instruction on how to compile that on your own...

Have fun...
