### ISSUE TITLE
Possible to set to blink/pulse mode? Send BPM?

### ISSUE THREAD

**Issue by nimaid** [FMMT666/launchpad.py#31]
I have a MkII. I usually use [Launchpad95 for Ableton ](http://motscousus.com/stuff/2011-07_Novation_Launchpad_Ableton_Live_Scripts/), and it is able to send alternate MIDI messages to the launchpad, in order to make a certain led solid, blink, or strobe to the BPM set over MIDI. 

That control script is Python, written for the Ableton scripting engine. It seems that sending the color code to channel 0 is for Solid, channel 1 is for Blink, and channel 2 is for Pulse.

Is there a builtin way to change the channel I send a color code to? If not, I may have some questions so I can try and add the feature myself. :)

**Comment by FMMT666** [comment]
Nope, that's not yet built in, but it might be added shortly.

\~scribbles note to add this feature during the holidays, next week\~

**Comment by nimaid** [comment]
That would be fantastic! I'm writing an open source middleman script to emulate Launchpad95 in any MIDI-enabled program, and it would be great to be able to add the tempo feedback to the LEDs. :) Thank you for the awesome library!

**Comment by FMMT666** [comment]
Just added

- LedCtrlPulseByCode( number, colorcode )
- LedCtrlFlashByCode( number, colorcode )

and put the rest (setting frequency, etc...) on the todo-list for the next days.

Unfortunately, there's no way to use RGB values instead of color codes for these commands,
as the Launchpads do no support that. I prepared some things for an RGB to color code conversion and as well having some color strings, e.g. "green", "red2", but...

...time is the enemy ¯\\\_(ツ)\_/¯

**Comment by nimaid** [comment]
That's awesome! Thank you! Yeah, it seems like Ableton/Launchpad95 send the launchpad a MIDI tempo message to set the rate, but I am not entirely sure. I do know that the blinking syncs perfectly with Ableton, on the beat, so yeah, probably MIDI tempo messages.

As for RGB, I personally find it more useful (and computationally efficient) to just use codes. I have saved 50 of them to a python module with names like "RED_THIRD", "RED", etc. Was about to add the remaining codes. It may make sense to add color codes to launchpad.py, so you could lp.LedCtrlXYByCode(0, 0, lp.BLUE). I might just add that to launchpad.py myself as a fork, and if you're interested, I could submit it as a pull request. Never contributed to another person's GitHub, so I am somewhat unfamilar with the process, but I can definitely match the coding style.

**Comment by FMMT666** [comment]
Today's update includes

- LedSetBpm( bpm )

with several restrictions due to timing constraints and the way the Launchpads handle the clock messages.

If I could had forseen the RGB variants years prior to their release, there now
would be tuples or lists instead of RGB arguments, but - well, here we are...

**Comment by nimaid** [comment]
Awesome! Can't wait to test it out! Hey, quick question, how long from a feature being added does it take to appear in a pip3 install of launchpad_py? I am probably going to include a copy of a working version of launchpad.py with my main project, but I would like to know how that whole update chain works.

**Comment by FMMT666** [comment]
I will add two more methods tomorrow (XYPulse/Flash), then run the
complete Kannix, mäcOS and Windoze tests and upload that to
PyPI on Sunday.

**Comment by FMMT666** [comment]
So, v0.8.1 with pulsing and flashing is now available via [PyPI](https://pypi.org/project/launchpad_py/#history).
It will take some time until it shows up in the (pip) index.

Or simply select the version manually...
`pip(2/3) install launchpad_py==0.8.1`
