### ISSUE TITLE
Refactoring?

### ISSUE THREAD

**Issue by haschdl** [FMMT666/launchpad.py#32]
Great job with the library! I know you did this on your free time, are you open to some refactoring?  It would make a lot easier to incorporate new features if it was modularized a bit. Currently it's one mega README file and one mega Python script.

**Comment by FMMT666** [comment]
Yes, it's ugly and should be cleaned up, I completely agree.
I didn't touch it yet because I had some problems in an
embedded Iron Python environment.

So far, I thought about splitting up the classes into single files
and tidy up the doc a bit (probably by doing the same splitting).

Is that what you thought of or do you have something different
in mind?

**Comment by haschdl** [comment]
That's what I thought @FMMT666 . Would you mind if I git a try to the documentation part and submit a PR?

**Comment by FMMT666** [comment]
Sure.
Could - could you possibly also clean my car?
