### ISSUE TITLE
How do i test if a button is pressed? i dont understand how to use ButtonStateXY

### ISSUE THREAD

**Issue by Nxllpointer** [FMMT666/launchpad.py#43]

**Comment by FMMT666** [comment]
assuming that "lp" is your Launchpad instance:

``` buts = lp.ButtonStateXY()```

If nothing is in the buffer, you get an empty list ```[]```, otherwise
one with three vars inside: ```[ <x>, <y>, <True/False> ]```.

So buts[0] is the x-coordinate of the matrix, buts[1] the y-coordinate
and buts[2] is either "True" or "False", depending on the state of the button
and wether it was pressed or released.
