### ISSUE TITLE
ButtonStateXY returning [] when pressing button on Launchpad Pro

### ISSUE THREAD

**Issue by CalleRC** [FMMT666/launchpad.py#54]
Hey

First i want to say that i love this project, and have been looking for something like this for a while.
Next: When using ButtonStateXY and pressing a button, the code program returns []

Example:
if lp.ButtonStateXY() != []:
     print(lp.ButtonStateXY()

This code returns: []

**Comment by FMMT666** [comment]
Yes, that's true.
You need to save the value of the first call, because any call to ButtonStateXY() removes
the current event from the receive buffer.

With Python 3.8 you could even assign and check the variable in one line,
known as the "Walrus Operator", "```:=```", but here's the more obvious variant.

```
  buts = lp.ButtonStateXY()   # this line removes the event from the buffer
  if buts != []:
    print( buts )
```

You also might take a look at some of the included examples.
