### ISSUE TITLE
Launchpad X AttributeError: 'NoneType' object has no attribute 'write_short'

### ISSUE THREAD

**Issue by V1K1NGbg** [FMMT666/launchpad.py#63]
no matter what I use I always get eather AttributeError: 'NoneType' object has no attribute 'write_short' or AttributeError: 'NoneType' object has no attribute 'write_sys_ex'

I am not sure what I do wrong

#

import sys
import random
from pygame import time
import launchpad

def main():

    mode = None

    lp = launchpad.Launchpad()
    if lp.Open(0, "LPX"):
        lp = launchpad.LaunchpadLPX()
        print("Launchpad X")
        mode = "Pro"

    if mode is None:
        print("Did not find any devices, meh...")
        return

    lp.LedAllOn(11)

    print("bye ...")

    lp.Reset()
    lp.Close()

if __name__ == '__main__':
    main()

Also, how to turn just one pixel forever
In the past there was LedCtrlRawByCode but now that doesn't exist

**Comment by FMMT666** [comment]
Yes, this code will not work, for two reasons:
a) You create an instance of Launchpad(), open the connection and then
override it with another one, LaunchpadLPX(), but without opening the device.
b) For the LPX, you have to open the first device with a "1", not a "0".

Here, this shall work:
```
lp = launchpad.LaunchpadLPX()
if lp.Open(1, "LPX"):
    print("Launchpad X")
    mode = "Pro"
...
```

Notice that your program above will quit immediately, so the LEDs
will probably only flash once and then turn off.

Also, you don't need this "mode" variable. This is only for the multi-device
demo code I wrote, because not all devices have the same features.

**Comment by V1K1NGbg** [comment]
Ouuuuuuu thanks so much.
What about the alternative for LedCtrlRawByCode

**Comment by FMMT666** [comment]
Yes, that's implemented and working fine.
Same for the new "Pulse" and "Flash" methods.

I just noticed that the codes in the documentation for the top row was wrong.
Corrected that.

11 is the lower left corner, 99 the top right (Novation logo).
Test:
```
for i in range(11,100):
  lp.LedCtrlRawByCode( i, i )
```

**Comment by V1K1NGbg** [comment]
Ouuuuuuu Thank you so much
