### ISSUE TITLE
Colorcodes not working Launchpad mini mk2.

### ISSUE THREAD

**Issue by RustySnek** [FMMT666/launchpad.py#65]
import launchpad_py as launchpad
import pygame
lp = launchpad.Launchpad()
lp.Open()
lp.Reset()
lp.LedAllOn(1)

Tried lp.LedAllOn( from 1 to 127 ) and everytime it glows orange.

**Comment by FMMT666** [comment]
Yes, that's not possible with the red/green devices.
"AllOn" really means "all on": Red + green = yellow.

The parameter was added for backwards compatibilty with the RGB variants.

**Comment by RustySnek** [comment]
Hmm I interpreted Allon as All leds on and colors inside. Is there anyway i can light up all with different colors?

**Comment by FMMT666** [comment]
I think the fastest way to do this is to use `LedCtrlRawRapid()`.
It takes a list with colorcodes and updates them all at once.
Make sure to use it in conjunction with `LedCtrlRawRapidHome()`,
that sets the operation back to the 1st LED (from the 8x8) matrix.

Otherwise, the next call to `...Rapid()` continues from where it last stopped.

```
  AllLEDs = [ lp.LedGetColor( 0, 3 ) ] * 80

  lp.LedCtrlRawRapidHome()
  lp.LedCtrlRawRapid( AllLEDs )
```

---
edit:
The LED update order is
  - 8x8 matrix top left to bottom right
  - right button column
  - top row, aka "automap buttons"

**Comment by RustySnek** [comment]
Ok Thanks.
